# Generated by Django 3.1.1 on 2020-09-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_one', models.PositiveSmallIntegerField(default=0)),
                ('rating_two', models.PositiveSmallIntegerField(default=0)),
                ('rating_three', models.PositiveSmallIntegerField(default=0)),
                ('rating_four', models.PositiveSmallIntegerField(default=0)),
                ('rating_five', models.PositiveSmallIntegerField(default=0)),
                ('rating_six', models.PositiveSmallIntegerField(default=0)),
                ('rating_seven', models.PositiveSmallIntegerField(default=0)),
                ('rating_eight', models.PositiveSmallIntegerField(default=0)),
                ('rating_nine', models.PositiveSmallIntegerField(default=0)),
                ('rating_ten', models.PositiveSmallIntegerField(default=0)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='students.student')),
            ],
        ),
    ]
