# Generated by Django 3.1.1 on 2020-09-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='Student',
            new_name='student',
        ),
    ]
