# Generated by Django 3.1.1 on 2020-09-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200920_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_eight',
            new_name='rating_1',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_five',
            new_name='rating_10',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_four',
            new_name='rating_2',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_nine',
            new_name='rating_3',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_one',
            new_name='rating_4',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_seven',
            new_name='rating_5',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_six',
            new_name='rating_6',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_ten',
            new_name='rating_7',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_three',
            new_name='rating_8',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rating_two',
            new_name='rating_9',
        ),
    ]
