# Generated by Django 3.1.1 on 2020-09-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200921_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.BooleanField(null=True),
        ),
    ]
