# Generated by Django 3.1.1 on 2020-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_8',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_9',
            field=models.FloatField(default=0),
        ),
    ]
