# Generated by Django 3.1.1 on 2020-09-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200918_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
